### ISSUE TITLE
SIGILL crash on pre-Haswell CPU

### ISSUE THREAD

**Issue by ColedanosTX** [3-manifolds/Sage_macOS#16] opened 2021-06-29 12:04 UTC
Attempted to install SageMath version 9.3 yesterday (June 28th ) and this morning (June 29th) but all attempts failed to run SageMath properly.

**Terminal output:** (Sage banner removed to avoid Markdown artifacts)
(no backtrace available)

Unhandled SIGILL: An illegal instruction occurred.
This probably occurred because a *compiled* module has a bug
in it and is not properly wrapped with sig_on(), sig_off().
Python will now terminate.

zsh: illegal hardware instruction  
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by culler** [comment] 2021-06-29 12:29
Please tell us something about your system.  Which processor does the "About This Mac" menu report?  Which version of macOS are you running?

Did you install the package named Recommended_9_3.pkg?  (If not, please do.) What happens if you run the command `sage -python` in your terminal?

**Comment by ColedanosTX** [comment] 2021-06-30 18:51
Hello Culler, thanks for the reply.
The macOS I am using is Big Sur 11.4
Yes, I did install the package Recommended_9_3.pkg right after installing SageMath.
Regarding your last question "What happens if you run the command sage -python in your terminal?", to answer I will need to download again SageMath 9.3 because I have uninstalled it after the failed attempts.

**Comment by culler** [comment] 2021-06-30 20:33
I am also running macOS 11.4, and I have multiple 11.4 systems on which I have installed the app.  I do not see issues with SIGILL on my systems, nor did many other people who have tested the app.  So please be aware that debugging this will most likely involve figuring out what are the unusual settings that you happen to have on your system.

In spite of the error message, this is probably not really caused by an illegal instruction.  My guess is that your system is killing the app because it failed to verify that the app's code signature satisfies the security restrictions that you have in place on your system.

If we are lucky this will be fixed by  downloading the disk image again.  But, also, please make sure that you have *not* configured your system to only allow apps downloaded from the App Store.  In the General tab of the Security and Privacy settings you should have the radio button checked which allows apps downloaded from "App store and identified developers".  And please make sure that you do not change any files in the application bundle.  It might also help to delete or move your ~/.sage directory before running the app and to remove any symlinks in /var/tmp which start with "sage-".  For example,

`% mv ~/.sage ~/DOT_sage`
`% rm /var/tmp/sage-9.3-current`

**Comment by culler** [comment] 2021-07-03 17:16
I disassembled libpython3.9 and found many calls to vmovapd, which is an AVX instruction.  Many of them reference addresses relative to dyld_stub_binder.  So possibly clang uses AVX instructions to speed up dynamic linking, meaning that they are ubiquitous.

**Comment by culler** [comment] 2021-07-03 19:26
This problem is most likely the same as #17, namely that your CPU is too old to support the AVX2 instruction set which is used by the app.  That would require a computer built in late 2013 or later.

**Comment by ColedanosTX** [comment] 2021-07-04 17:29
Thanks Marc for the comprehensive response to allow me the get arround the
installation problem I am experiencing with Sage.

My Macbook was bought mid 2014.

I will try to do per your instructions.

Many thanks for your attention and time on this issue.
Regards
Thomas Coledanos

**Comment by culler** [comment] 2021-08-03 17:14
I am going to close the other tickets related to SIGILL crashes and leave this one open.

I was finally able to reproduce these crashes on a late 2008 Macbook Pro.  I discovered that it is not enough to disable AVX2 intructions.  It is also necessary to disable BMI2 instructions.  I am currently recompiling sage with both of those disabled and will test on the 2008 computer.  If that works I will replace the Sage-9.4 release candidate binaries.

It turns out that Apple was selling Macbook Pros with Ivy Bridge processors until 2016, and they are still selling Mac Pro computers with Xeon.  Those processors do not support either AVX2 or BMI2.

**Comment by NathanDunfield** [comment] 2021-08-03 17:53
> It turns out that Apple was selling Macbook Pros with Ivy Bridge processors until 2016, and they are still selling Mac Pro computers with Xeon. Those processors do not support either AVX2 or BMI2.

Xeon is just Intel's name for the highest performance processors in each family, instead of calling them "Core i11" or whatever.  Any Xeon chip past Ivy Bridge should be fine --- I've had no issues with the app on a 2017 iMac Pro which has Xeon from the Skylake-W series.

**Comment by culler** [comment] 2021-08-03 18:12
OK, fair enough.  However, this [wikipedia page](https://en.wikipedia.org/wiki/List_of_Macintosh_models_grouped_by_CPU_type) says that the Xeon ES v2, which is an Ivy Bridge processor (with up to 12 cores), is currently being used in at least some models of the Mac Pro.

Also worth noting (from the same page) is that Apple used an Ivy Bridge 2-core Core I7 processor in some MacBook Pro models that were made as late as October 2016.  And MacBook Pro models from late 2013 onward are supposedly compatible with Big Sur.  So if we allow AVX2 or BMI2 instructions then we cannot be sure even that all Big Sur systems can run the SageMath app.  To me that means we are really forced to disable those instructions.

**Comment by NathanDunfield** [comment] 2021-08-03 18:52
> OK, fair enough. However, this [wikipedia page](https://en.wikipedia.org/wiki/List_of_Macintosh_models_grouped_by_CPU_type) says that the Xeon ES v2, which is an Ivy Bridge processor (with up to 12 cores), is currently being used in at least some models of the Mac Pro.

No, the [small cylindrical Mac Pro](https://en.wikipedia.org/wiki/Mac_Pro) which had these processors was formally discontinued in late 2019, and for nearly all purposes it had been replaced by the [iMacPro](https://en.wikipedia.org/wiki/IMac_Pro) in late 2017.   But it did have the longest run of any Mac model ever, almost 6 years.  I do have one of these Mac Pros, but it's currently running 10.12 so I can't use it to test the Sage app.

**Comment by NathanDunfield** [comment] 2021-08-03 18:55
Also, I meant to add that I do agree that the app should avoid AVX2 and BMI2 instructions for maximum compatibility.

**Comment by culler** [comment] 2021-08-03 19:00
For what it is worth (I will know more soon) I had no trouble installing
the SageMath-9-4.app on my 2008 Macbook Pro running 10.11.  (It did take
half a day to get El Capitan installed, though.)  I got the normal "This
app was downloaded from the internet" warning,  and it launched fine when I
agreed.  The crash did not occur until libgmp was loaded.

**Comment by culler** [comment] 2021-08-03 20:28
I am still getting illegal instructions in gmp, but the instruction is different.  This time it is vzeroupper.  So I am hopefull that a few more rounds of disabling various intel features and recompiling will eventually fix this.

The installation works fine on El Capitan, but it takes a really long time to verify the app.  Eventually it succeeds.

**Comment by wtworden** [comment] 2021-08-05 17:05
Hi Marc,
I am having the same issue on a late 2013 iMac running 11.14.3. The processor is a Haswell/Crystalwell (according to everymac.com). I have tried both SageMath-9-4.dmg and SageMath-9-3.dmg. I'm not sure if the current version of 9-4 has the fixes you talked about above, but in any case I thought another data point might be helpful.

-Will

**Comment by culler** [comment] 2021-08-05 19:33
I have replaced the disk image for the Sage 9.4 prerelease with a new one which was compiled without avx, avx2 or bmi2
instructions.  Our tests indicate that this fixes the SIGILL issues, so I am closing this ticket.  Please reopen the ticket if an illegal instruction crash occurs with the new version.

**Closed by culler** 2021-08-05 19:33 UTC
Labels: CPU
